SQL3501W  The table space(s) in which the table resides will not be placed in 
backup pending state since forward recovery is disabled for the database.

SQL3109N  The utility is beginning to load data from file 
"C:\\Users\\viraj\\Desktop\\TODB-CSE532\\Assignment-3\\COVID19testingsi".

SQL3500W  The utility is beginning the "LOAD" phase at time "10/30/2020 
21:20:37.932877".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3120W  The value in row "F0-1" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-1" of 
the input file.

SQL3120W  The value in row "F0-2" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-2" of 
the input file.

SQL3120W  The value in row "F0-3" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-3" of 
the input file.

SQL3120W  The value in row "F0-4" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-4" of 
the input file.

SQL3120W  The value in row "F0-5" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-5" of 
the input file.

SQL3120W  The value in row "F0-6" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-6" of 
the input file.

SQL3120W  The value in row "F0-7" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-7" of 
the input file.

SQL3120W  The value in row "F0-8" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-8" of 
the input file.

SQL3120W  The value in row "F0-9" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-9" of 
the input file.

SQL3120W  The value in row "F0-10" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-10" 
of the input file.

SQL3120W  The value in row "F0-11" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-11" 
of the input file.

SQL3120W  The value in row "F0-12" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-12" 
of the input file.

SQL3120W  The value in row "F0-13" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-13" 
of the input file.

SQL3120W  The value in row "F0-14" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-14" 
of the input file.

SQL3120W  The value in row "F0-15" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-15" 
of the input file.

SQL3120W  The value in row "F0-16" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-16" 
of the input file.

SQL3120W  The value in row "F0-17" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-17" 
of the input file.

SQL3120W  The value in row "F0-18" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-18" 
of the input file.

SQL3120W  The value in row "F0-19" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-19" 
of the input file.

SQL3120W  The value in row "F0-20" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-20" 
of the input file.

SQL3120W  The value in row "F0-21" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-21" 
of the input file.

SQL3120W  The value in row "F0-22" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-22" 
of the input file.

SQL3120W  The value in row "F0-23" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-23" 
of the input file.

SQL3120W  The value in row "F0-24" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-24" 
of the input file.

SQL3120W  The value in row "F0-25" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-25" 
of the input file.

SQL3120W  The value in row "F0-26" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-26" 
of the input file.

SQL3120W  The value in row "F0-27" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-27" 
of the input file.

SQL3120W  The value in row "F0-28" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-28" 
of the input file.

SQL3120W  The value in row "F0-29" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-29" 
of the input file.

SQL3120W  The value in row "F0-30" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-30" 
of the input file.

SQL3120W  The value in row "F0-31" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-31" 
of the input file.

SQL3120W  The value in row "F0-32" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-32" 
of the input file.

SQL3120W  The value in row "F0-33" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-33" 
of the input file.

SQL3120W  The value in row "F0-34" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-34" 
of the input file.

SQL3120W  The value in row "F0-35" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-35" 
of the input file.

SQL3120W  The value in row "F0-36" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-36" 
of the input file.

SQL3120W  The value in row "F0-37" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-37" 
of the input file.

SQL3120W  The value in row "F0-38" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-38" 
of the input file.

SQL3120W  The value in row "F0-39" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-39" 
of the input file.

SQL3120W  The value in row "F0-40" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-40" 
of the input file.

SQL3120W  The value in row "F0-41" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-41" 
of the input file.

SQL3120W  The value in row "F0-42" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-42" 
of the input file.

SQL3120W  The value in row "F0-43" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-43" 
of the input file.

SQL3120W  The value in row "F0-44" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-44" 
of the input file.

SQL3120W  The value in row "F0-45" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-45" 
of the input file.

SQL3120W  The value in row "F0-46" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-46" 
of the input file.

SQL3120W  The value in row "F0-47" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-47" 
of the input file.

SQL3120W  The value in row "F0-48" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-48" 
of the input file.

SQL3120W  The value in row "F0-49" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-49" 
of the input file.

SQL3120W  The value in row "F0-50" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-50" 
of the input file.

SQL3120W  The value in row "F0-51" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-51" 
of the input file.

SQL3120W  The value in row "F0-52" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-52" 
of the input file.

SQL3120W  The value in row "F0-53" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-53" 
of the input file.

SQL3120W  The value in row "F0-54" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-54" 
of the input file.

SQL3120W  The value in row "F0-55" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-55" 
of the input file.

SQL3120W  The value in row "F0-56" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-56" 
of the input file.

SQL3120W  The value in row "F0-57" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-57" 
of the input file.

SQL3120W  The value in row "F0-58" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-58" 
of the input file.

SQL3120W  The value in row "F0-59" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-59" 
of the input file.

SQL3120W  The value in row "F0-60" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-60" 
of the input file.

SQL3120W  The value in row "F0-61" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-61" 
of the input file.

SQL3120W  The value in row "F0-62" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-62" 
of the input file.

SQL3120W  The value in row "F0-63" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-63" 
of the input file.

SQL3120W  The value in row "F0-64" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-64" 
of the input file.

SQL3120W  The value in row "F0-65" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-65" 
of the input file.

SQL3120W  The value in row "F0-66" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-66" 
of the input file.

SQL3120W  The value in row "F0-67" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-67" 
of the input file.

SQL3120W  The value in row "F0-68" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-68" 
of the input file.

SQL3120W  The value in row "F0-69" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-69" 
of the input file.

SQL3120W  The value in row "F0-70" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-70" 
of the input file.

SQL3120W  The value in row "F0-71" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-71" 
of the input file.

SQL3120W  The value in row "F0-72" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-72" 
of the input file.

SQL3120W  The value in row "F0-73" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-73" 
of the input file.

SQL3120W  The value in row "F0-74" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-74" 
of the input file.

SQL3120W  The value in row "F0-75" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-75" 
of the input file.

SQL3120W  The value in row "F0-76" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-76" 
of the input file.

SQL3120W  The value in row "F0-77" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-77" 
of the input file.

SQL3120W  The value in row "F0-78" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-78" 
of the input file.

SQL3120W  The value in row "F0-79" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-79" 
of the input file.

SQL3120W  The value in row "F0-80" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-80" 
of the input file.

SQL3120W  The value in row "F0-81" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-81" 
of the input file.

SQL3120W  The value in row "F0-82" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-82" 
of the input file.

SQL3120W  The value in row "F0-83" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-83" 
of the input file.

SQL3120W  The value in row "F0-84" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-84" 
of the input file.

SQL3120W  The value in row "F0-85" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-85" 
of the input file.

SQL3120W  The value in row "F0-86" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-86" 
of the input file.

SQL3120W  The value in row "F0-87" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-87" 
of the input file.

SQL3120W  The value in row "F0-88" and column "1" could not be converted to an 
integer value, and the target column is not nullable, so the row was not 
loaded.

SQL3185W  The previous error occurred while processing data from row "F0-88" 
of the input file.

SQL3227W  Record token "F0-1" refers to user record number "1".

SQL3227W  Record token "F0-2" refers to user record number "2".

SQL3227W  Record token "F0-3" refers to user record number "3".

SQL3227W  Record token "F0-4" refers to user record number "4".

SQL3227W  Record token "F0-5" refers to user record number "5".

SQL3227W  Record token "F0-6" refers to user record number "6".

SQL3227W  Record token "F0-7" refers to user record number "7".

SQL3227W  Record token "F0-8" refers to user record number "8".

SQL3227W  Record token "F0-9" refers to user record number "9".

SQL3227W  Record token "F0-10" refers to user record number "10".

SQL3227W  Record token "F0-11" refers to user record number "11".

SQL3227W  Record token "F0-12" refers to user record number "12".

SQL3227W  Record token "F0-13" refers to user record number "13".

SQL3227W  Record token "F0-14" refers to user record number "14".

SQL3227W  Record token "F0-15" refers to user record number "15".

SQL3227W  Record token "F0-16" refers to user record number "16".

SQL3227W  Record token "F0-17" refers to user record number "17".

SQL3227W  Record token "F0-18" refers to user record number "18".

SQL3227W  Record token "F0-19" refers to user record number "19".

SQL3227W  Record token "F0-20" refers to user record number "20".

SQL3227W  Record token "F0-21" refers to user record number "21".

SQL3227W  Record token "F0-22" refers to user record number "22".

SQL3227W  Record token "F0-23" refers to user record number "23".

SQL3227W  Record token "F0-24" refers to user record number "24".

SQL3227W  Record token "F0-25" refers to user record number "25".

SQL3227W  Record token "F0-26" refers to user record number "26".

SQL3227W  Record token "F0-27" refers to user record number "27".

SQL3227W  Record token "F0-28" refers to user record number "28".

SQL3227W  Record token "F0-29" refers to user record number "29".

SQL3227W  Record token "F0-30" refers to user record number "30".

SQL3227W  Record token "F0-31" refers to user record number "31".

SQL3227W  Record token "F0-32" refers to user record number "32".

SQL3227W  Record token "F0-33" refers to user record number "33".

SQL3227W  Record token "F0-34" refers to user record number "34".

SQL3227W  Record token "F0-35" refers to user record number "35".

SQL3227W  Record token "F0-36" refers to user record number "36".

SQL3227W  Record token "F0-37" refers to user record number "37".

SQL3227W  Record token "F0-38" refers to user record number "38".

SQL3227W  Record token "F0-39" refers to user record number "39".

SQL3227W  Record token "F0-40" refers to user record number "40".

SQL3227W  Record token "F0-41" refers to user record number "41".

SQL3227W  Record token "F0-42" refers to user record number "42".

SQL3227W  Record token "F0-43" refers to user record number "43".

SQL3227W  Record token "F0-44" refers to user record number "44".

SQL3227W  Record token "F0-45" refers to user record number "45".

SQL3227W  Record token "F0-46" refers to user record number "46".

SQL3227W  Record token "F0-47" refers to user record number "47".

SQL3227W  Record token "F0-48" refers to user record number "48".

SQL3227W  Record token "F0-49" refers to user record number "49".

SQL3227W  Record token "F0-50" refers to user record number "50".

SQL3227W  Record token "F0-51" refers to user record number "51".

SQL3227W  Record token "F0-52" refers to user record number "52".

SQL3227W  Record token "F0-53" refers to user record number "53".

SQL3227W  Record token "F0-54" refers to user record number "54".

SQL3227W  Record token "F0-55" refers to user record number "55".

SQL3227W  Record token "F0-56" refers to user record number "56".

SQL3227W  Record token "F0-57" refers to user record number "57".

SQL3227W  Record token "F0-58" refers to user record number "58".

SQL3227W  Record token "F0-59" refers to user record number "59".

SQL3227W  Record token "F0-60" refers to user record number "60".

SQL3227W  Record token "F0-61" refers to user record number "61".

SQL3227W  Record token "F0-62" refers to user record number "62".

SQL3227W  Record token "F0-63" refers to user record number "63".

SQL3227W  Record token "F0-64" refers to user record number "64".

SQL3227W  Record token "F0-65" refers to user record number "65".

SQL3227W  Record token "F0-66" refers to user record number "66".

SQL3227W  Record token "F0-67" refers to user record number "67".

SQL3227W  Record token "F0-68" refers to user record number "68".

SQL3227W  Record token "F0-69" refers to user record number "69".

SQL3227W  Record token "F0-70" refers to user record number "70".

SQL3227W  Record token "F0-71" refers to user record number "71".

SQL3227W  Record token "F0-72" refers to user record number "72".

SQL3227W  Record token "F0-73" refers to user record number "73".

SQL3227W  Record token "F0-74" refers to user record number "74".

SQL3227W  Record token "F0-75" refers to user record number "75".

SQL3227W  Record token "F0-76" refers to user record number "76".

SQL3227W  Record token "F0-77" refers to user record number "77".

SQL3227W  Record token "F0-78" refers to user record number "78".

SQL3227W  Record token "F0-79" refers to user record number "79".

SQL3227W  Record token "F0-80" refers to user record number "80".

SQL3227W  Record token "F0-81" refers to user record number "81".

SQL3227W  Record token "F0-82" refers to user record number "82".

SQL3227W  Record token "F0-83" refers to user record number "83".

SQL3227W  Record token "F0-84" refers to user record number "84".

SQL3227W  Record token "F0-85" refers to user record number "85".

SQL3227W  Record token "F0-86" refers to user record number "86".

SQL3227W  Record token "F0-87" refers to user record number "87".

SQL3227W  Record token "F0-88" refers to user record number "88".

SQL3110N  The utility has completed processing.  "88" rows were read from the 
input file.

SQL3519W  Begin Load Consistency Point. Input record count = "88".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "10/30/2020 
21:20:37.939683".

SQL3500W  The utility is beginning the "BUILD" phase at time "10/30/2020 
21:20:37.940391".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "10/30/2020 
21:20:37.951160".

SQL3107W  At least one warning message was encountered during LOAD processing.


Number of rows read         = 88
Number of rows skipped      = 0
Number of rows loaded       = 0
Number of rows rejected     = 88
Number of rows deleted      = 0
Number of rows committed    = 88

SQL3501W  The table space(s) in which the table resides will not be placed in 
backup pending state since forward recovery is disabled for the database.

SQL3109N  The utility is beginning to load data from file 
"C:\\Users\\viraj\\Desktop\\TODB-CSE532\\Assignment-3\\COVID19testingsi".

SQL3500W  The utility is beginning the "LOAD" phase at time "10/30/2020 
21:24:08.536217".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3125W  The character data in row "F0-1" and column "5" was truncated 
because the data is longer than the target database column.

SQL3119W  The value in row "F0-1" and column "6" could not be converted to an 
integer value, so a null value was loaded instead.

SQL3125W  The character data in row "F0-1" and column "7" was truncated 
because the data is longer than the target database column.

SQL3123W  The field value in row "F0-1" and column "8" cannot be converted to 
a PACKED DECIMAL value.  A null was loaded.

SQL3123W  The field value in row "F0-1" and column "9" cannot be converted to 
a PACKED DECIMAL value.  A null was loaded.

SQL3227W  Record token "F0-1" refers to user record number "1".

SQL3110N  The utility has completed processing.  "88" rows were read from the 
input file.

SQL3519W  Begin Load Consistency Point. Input record count = "88".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "10/30/2020 
21:24:08.542723".

SQL3107W  At least one warning message was encountered during LOAD processing.


Number of rows read         = 88
Number of rows skipped      = 0
Number of rows loaded       = 88
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 88

