db2 create database dea

============createdeatable.sql===============
CREATE TABLE cse532.dea(
REPORTER_DEA_NO VARCHAR(150)  NOT NULL,
REPORTER_BUS_ACT VARCHAR(50),
REPORTER_NAME VARCHAR(50),
REPORTER_ADDL_CO_INFO VARCHAR(50),
REPORTER_ADDRESS1 VARCHAR(150),
REPORTER_ADDRESS2 VARCHAR(150),
REPORTER_CITY VARCHAR(50),
REPORTER_STATE VARCHAR(50),
REPORTER_ZIP BIGINT ,
REPORTER_COUNTY VARCHAR(50),
BUYER_DEA_NO VARCHAR(50),
BUYER_BUS_ACT VARCHAR(50),
BUYER_NAME VARCHAR(150),
BUYER_ADDL_CO_INFO VARCHAR(100),
BUYER_ADDRESS1 VARCHAR(100),
BUYER_ADDRESS2 VARCHAR(100),
BUYER_CITY VARCHAR(100),
BUYER_STATE VARCHAR(100),
BUYER_ZIP BIGINT,
BUYER_COUNTY VARCHAR(50),
TRANSACTION_CODE VARCHAR(100),
DRUG_CODE INT,
NDC_NO VARCHAR(50),
DRUG_NAME VARCHAR(50),
QUANTITY INT,
UNIT VARCHAR(50),
ACTION_INDICATOR VARCHAR(50),
ORDER_FORM_NO VARCHAR(50),
CORRECTION_NO VARCHAR(50),
STRENGTH VARCHAR(5),
TRANSACTION_DATE DATE,
CALC_BASE_WT_IN_GM DOUBLE,
DOSAGE_UNIT BIGINT,
TRANSACTION_ID BIGINT NOT NULL,
Product_Name VARCHAR(50),
Ingredient_Name VARCHAR(150),
Measure VARCHAR(50),
MME_Conversion_Factor FLOAT,
Combined_Labeler_Name VARCHAR(50),
Reporter_family VARCHAR(50),
dos_str VARCHAR(50),
MME FLOAT,
) COMPRESS YES

============createzip.sql===============
CREATE TABLE cse532.zip(
zip INT,
county VARCHAR(50),
irs_estimated_population_2015 BIGINT
)





