select  BUYER_STATE,BUYER_COUNTY, MONTH(TRANSACTION_DATE) AS MONTH_NUM,YEAR(TRANSACTION_DATE) AS YEAR_NUM, SUM(DOSAGE_UNIT) as TOTAL_PILLS from cse532.dea GROUP BY (MONTH(TRANSACTION_DATE),YEAR(TRANSACTION_DATE),BUYER_COUNTY,BUYER_STATE)


