SELECT MONTHLY_SUM, AVG(MONTHLY_SUM) OVER (ORDER BY YEARDATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW ) AS SMOOTH FROM
    (SELECT SUM(DOSAGE_UNIT) AS MONTHLY_SUM,YEARDATE FROM
        (SELECT
        YEAR(TRANSACTION_DATE) ||
        CASE 
            WHEN (  CAST( MONTH(TRANSACTION_DATE) AS INT)  < 10 ) 
                 THEN '0'  || CAST( MONTH(TRANSACTION_DATE) AS INT)
            ELSE CAST ( MONTH(TRANSACTION_DATE) AS CHAR(2) )
        END AS YEARDATE,
        DOSAGE_UNIT
        from CSE532.DEA 
        WHERE BUYER_COUNTY = 'PIKE' AND BUYER_STATE='KY') 
    GROUP BY YEARDATE)